### PR TITLE
feat(base-cluster): support aws route53 for DNS

### LINKED ISSUE #31: Route53 Support
Hello there! 

thanks for sharing the helm charts. ;)
I wanted to ask kindle for Route53 Support.

### PR DESCRIPTION
**Pull request by cwrau**
Closes #31

### CODE REVIEW

**Comment by cwrau** [comment]
@barrynorman Can you take a look at this? I can't test AWS myself 😅

**Comment by barrynorman** [comment]
looks like its working.

**Comment by mstroecker** [comment]
@barrynorman Currently, we do not use Route53, and we'd like to keep this chart simple and testable for us. @cwrau is now working on a different chart, which I'd like to recommend to you. It might also meet your requirements. Otherwise, feel free to use this repo and the changes from this PR as a fork.

Chart: https://github.com/teutonet/teutonet-helm-charts

**Comment by barrynorman** [comment]
Then I would recommend not to offer it to the public if you don't want to change things in your chart. IMHO ;)

Nevermind. I'll create my own.
Thanks.

**Pull request closed without merging**
